changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - ci
    - title: Other Changes
      labels:
        - "*"
